2019-06-21 08:29:41.005 [error] <0.1269.0> gen_server <0.1269.0> terminated with reason: {socket_error,timeout}
2019-06-21 08:29:41.005 [error] <0.1269.0> CRASH REPORT Process <0.1269.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-06-21 08:29:41.005 [error] <0.1264.0> gen_server <0.1264.0> terminated with reason: {socket_error,timeout}
2019-06-21 08:29:41.006 [error] <0.1263.0> Supervisor {<0.1263.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.103>, <0.1264.0>, <0.1267.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61618 -> 127.0.0.1:5672">>) at <0.1269.0> exit with reason {socket_error,timeout} in context child_terminated
2019-06-21 08:29:41.006 [error] <0.1263.0> Supervisor {<0.1263.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.103>, <0.1264.0>, <0.1267.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61618 -> 127.0.0.1:5672">>) at <0.1269.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-21 08:29:41.006 [error] <0.1264.0> CRASH REPORT Process <0.1264.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-06-21 08:29:41.006 [error] <0.1262.0> Supervisor {<0.1262.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1263.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.1264.0> exit with reason {socket_error,timeout} in context child_terminated
2019-06-21 08:29:41.006 [error] <0.1262.0> Supervisor {<0.1262.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1263.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.1264.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-21 08:32:11.002 [error] <0.1338.0> gen_server <0.1338.0> terminated with reason: {socket_error,timeout}
2019-06-21 08:32:11.002 [error] <0.1333.0> gen_server <0.1333.0> terminated with reason: {socket_error,timeout}
2019-06-21 08:32:11.003 [error] <0.1338.0> CRASH REPORT Process <0.1338.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-06-21 08:32:11.003 [error] <0.1332.0> Supervisor {<0.1332.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.104>, <0.1333.0>, <0.1336.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:54420 -> 127.0.0.1:5672">>) at <0.1338.0> exit with reason {socket_error,timeout} in context child_terminated
2019-06-21 08:32:11.004 [error] <0.1332.0> Supervisor {<0.1332.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.104>, <0.1333.0>, <0.1336.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:54420 -> 127.0.0.1:5672">>) at <0.1338.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-21 08:32:11.004 [error] <0.1333.0> CRASH REPORT Process <0.1333.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-06-21 08:32:11.004 [error] <0.1331.0> Supervisor {<0.1331.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1332.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.1333.0> exit with reason {socket_error,timeout} in context child_terminated
2019-06-21 08:32:11.004 [error] <0.1331.0> Supervisor {<0.1331.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1332.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.1333.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-21 09:25:18.004 [error] <0.1358.0> gen_server <0.1358.0> terminated with reason: {socket_error,timeout}
2019-06-21 09:25:18.004 [error] <0.1358.0> CRASH REPORT Process <0.1358.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-06-21 09:25:18.004 [error] <0.1354.0> gen_server <0.1354.0> terminated with reason: {socket_error,timeout}
2019-06-21 09:25:18.004 [error] <0.1353.0> Supervisor {<0.1353.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.106>, <0.1354.0>, <0.1356.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:54662 -> 127.0.0.1:5672">>) at <0.1358.0> exit with reason {socket_error,timeout} in context child_terminated
2019-06-21 09:25:18.004 [error] <0.1353.0> Supervisor {<0.1353.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.106>, <0.1354.0>, <0.1356.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:54662 -> 127.0.0.1:5672">>) at <0.1358.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-21 09:25:18.004 [error] <0.1354.0> CRASH REPORT Process <0.1354.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-06-21 09:25:18.005 [error] <0.1352.0> Supervisor {<0.1352.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1353.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.1354.0> exit with reason {socket_error,timeout} in context child_terminated
2019-06-21 09:25:18.005 [error] <0.1352.0> Supervisor {<0.1352.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1353.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.1354.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-21 09:25:18.005 [error] <0.1352.0> Supervisor {<0.1352.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.1353.0> exit with reason shutdown in context shutdown_error
2019-06-21 09:29:19.009 [error] <0.1409.0> gen_server <0.1409.0> terminated with reason: {socket_error,timeout}
2019-06-21 09:29:19.009 [error] <0.1409.0> CRASH REPORT Process <0.1409.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-06-21 09:29:19.009 [error] <0.1405.0> gen_server <0.1405.0> terminated with reason: {socket_error,timeout}
2019-06-21 09:29:19.009 [error] <0.1404.0> Supervisor {<0.1404.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.108>, <0.1405.0>, <0.1407.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58264 -> 127.0.0.1:5672">>) at <0.1409.0> exit with reason {socket_error,timeout} in context child_terminated
2019-06-21 09:29:19.009 [error] <0.1404.0> Supervisor {<0.1404.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.108>, <0.1405.0>, <0.1407.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58264 -> 127.0.0.1:5672">>) at <0.1409.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-21 09:29:19.010 [error] <0.1405.0> CRASH REPORT Process <0.1405.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-06-21 09:29:19.010 [error] <0.1403.0> Supervisor {<0.1403.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1404.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.1405.0> exit with reason {socket_error,timeout} in context child_terminated
2019-06-21 09:29:19.010 [error] <0.1403.0> Supervisor {<0.1403.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1404.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.1405.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-21 09:30:30.007 [error] <0.1428.0> gen_server <0.1428.0> terminated with reason: {socket_error,timeout}
2019-06-21 09:30:30.007 [error] <0.1428.0> CRASH REPORT Process <0.1428.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-06-21 09:30:30.007 [error] <0.1424.0> gen_server <0.1424.0> terminated with reason: {socket_error,timeout}
2019-06-21 09:30:30.008 [error] <0.1423.0> Supervisor {<0.1423.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.110>, <0.1424.0>, <0.1426.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58331 -> 127.0.0.1:5672">>) at <0.1428.0> exit with reason {socket_error,timeout} in context child_terminated
2019-06-21 09:30:30.008 [error] <0.1423.0> Supervisor {<0.1423.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.110>, <0.1424.0>, <0.1426.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58331 -> 127.0.0.1:5672">>) at <0.1428.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-21 09:30:30.008 [error] <0.1424.0> CRASH REPORT Process <0.1424.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-06-21 09:30:30.009 [error] <0.1422.0> Supervisor {<0.1422.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1423.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.1424.0> exit with reason {socket_error,timeout} in context child_terminated
2019-06-21 09:30:30.010 [error] <0.1422.0> Supervisor {<0.1422.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1423.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.1424.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-21 09:52:53.004 [error] <0.1442.0> gen_server <0.1442.0> terminated with reason: {socket_error,timeout}
2019-06-21 09:52:53.004 [error] <0.1446.0> gen_server <0.1446.0> terminated with reason: {socket_error,timeout}
2019-06-21 09:52:53.005 [error] <0.1446.0> CRASH REPORT Process <0.1446.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-06-21 09:52:53.005 [error] <0.1441.0> Supervisor {<0.1441.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.112>, <0.1442.0>, <0.1444.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58393 -> 127.0.0.1:5672">>) at <0.1446.0> exit with reason {socket_error,timeout} in context child_terminated
2019-06-21 09:52:53.005 [error] <0.1441.0> Supervisor {<0.1441.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.112>, <0.1442.0>, <0.1444.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58393 -> 127.0.0.1:5672">>) at <0.1446.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-21 09:52:53.005 [error] <0.1442.0> CRASH REPORT Process <0.1442.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-06-21 09:52:53.006 [error] <0.1440.0> Supervisor {<0.1440.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1441.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.1442.0> exit with reason {socket_error,timeout} in context child_terminated
2019-06-21 09:52:53.006 [error] <0.1440.0> Supervisor {<0.1440.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1441.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.1442.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-21 09:53:41.457 [warning] <0.1461.0> Connection (<0.1461.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server
2019-06-21 09:53:41.458 [error] <0.1462.0> Supervisor {<0.1462.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(network, <0.1461.0>, <<"client 127.0.0.1:58458 -> 127.0.0.1:5672">>) at undefined exit with reason shutdown in context shutdown_error
